import unittest
from unittest.mock import MagicMock, patch
import sys
import os

current = os.path.dirname(os.path.realpath(__file__))
parent = os.path.dirname(current)
sys.path.append(parent)

from spoonacular import *

INPUT = "INPUT"
EXPECTED_OUTPUT = "EXPECTED_OUTPUT"


class SearchRecipeByIngredTests(unittest.TestCase):
    def test_search_recipe_by_ingred(self):
        with patch("spoonacular.requests.get") as mock_requests_get:
            mock_response = MagicMock()

            mock_response.json.side_effect = [
                {},
                [
                    {
                        "id": 640352,
                        "title": "Cranberry Apple Crisp",
                        "image": "https://spoonacular.com/recipeImages/640352-312x231.jpg",
                        "imageType": "jpg",
                        "usedIngredientCount": 1,
                        "missedIngredientCount": 3,
                        "missedIngredients": [
                            {
                                "id": 9078,
                                "amount": 2.0,
                                "unit": "cups",
                                "unitLong": "cups",
                                "unitShort": "cup",
                                "aisle": "Produce",
                                "name": "cranberries",
                                "original": "2 cups fresh cranberries",
                                "originalString": "2 cups fresh cranberries",
                                "originalName": "fresh cranberries",
                                "metaInformation": ["fresh"],
                                "meta": ["fresh"],
                                "extendedName": "fresh cranberries",
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/cranberries.jpg",
                            },
                            {
                                "id": 1145,
                                "amount": 4.0,
                                "unit": "Tbs",
                                "unitLong": "Tbs",
                                "unitShort": "Tbs",
                                "aisle": "Milk, Eggs, Other Dairy",
                                "name": "unsalted butter",
                                "original": "1/2 stick (4 Tbs) unsalted butter, cut into cubes",
                                "originalString": "1/2 stick (4 Tbs) unsalted butter, cut into cubes",
                                "originalName": "1/2 stick unsalted butter, cut into cubes",
                                "metaInformation": ["unsalted", "cut into cubes"],
                                "meta": ["unsalted", "cut into cubes"],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/butter-sliced.jpg",
                            },
                            {
                                "id": 8120,
                                "amount": 1.5,
                                "unit": "cups",
                                "unitLong": "cups",
                                "unitShort": "cup",
                                "aisle": "Cereal",
                                "name": "oats",
                                "original": "1 1/2 cups regular oats (not quick-cooking)",
                                "originalString": "1 1/2 cups regular oats (not quick-cooking)",
                                "originalName": "regular oats (not quick-cooking)",
                                "metaInformation": ["(not quick-cooking)"],
                                "meta": ["(not quick-cooking)"],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/rolled-oats.jpg",
                            },
                        ],
                        "usedIngredients": [
                            {
                                "id": 1089003,
                                "amount": 4.0,
                                "unit": "cups",
                                "unitLong": "cups",
                                "unitShort": "cup",
                                "aisle": "Produce",
                                "name": "granny smith apples",
                                "original": "4 cups Granny Smith apples, chopped into ½ inch chunks",
                                "originalString": "4 cups Granny Smith apples, chopped into ½ inch chunks",
                                "originalName": "Granny Smith apples, chopped into ½ inch chunks",
                                "metaInformation": ["chopped"],
                                "meta": ["chopped"],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/grannysmith-apple.png",
                            }
                        ],
                        "unusedIngredients": [],
                        "likes": 11,
                    },
                    {
                        "id": 632660,
                        "title": "Apricot Glazed Apple Tart",
                        "image": "https://spoonacular.com/recipeImages/632660-312x231.jpg",
                        "imageType": "jpg",
                        "usedIngredientCount": 1,
                        "missedIngredientCount": 3,
                        "missedIngredients": [
                            {
                                "id": 1001,
                                "amount": 1.5,
                                "unit": "sticks",
                                "unitLong": "sticks",
                                "unitShort": "sticks",
                                "aisle": "Milk, Eggs, Other Dairy",
                                "name": "butter",
                                "original": "1 1/2 sticks cold unsalted butter cold unsalted butter<",
                                "originalString": "1 1/2 sticks cold unsalted butter cold unsalted butter<",
                                "originalName": "cold unsalted butter cold unsalted butter",
                                "metaInformation": ["unsalted", "cold"],
                                "meta": ["unsalted", "cold"],
                                "extendedName": "unsalted butter",
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/butter-sliced.jpg",
                            },
                            {
                                "id": 2010,
                                "amount": 2.0,
                                "unit": "teaspoons",
                                "unitLong": "teaspoons",
                                "unitShort": "tsp",
                                "aisle": "Spices and Seasonings",
                                "name": "cinnamon",
                                "original": "2 teaspoons cinnamon",
                                "originalString": "2 teaspoons cinnamon",
                                "originalName": "cinnamon",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
                            },
                            {
                                "id": 19719,
                                "amount": 2.0,
                                "unit": "tablespoons",
                                "unitLong": "tablespoons",
                                "unitShort": "Tbsp",
                                "aisle": "Nut butters, Jams, and Honey",
                                "name": "apricot preserves",
                                "original": "2 tablespoons apricot preserves, melted and strained",
                                "originalString": "2 tablespoons apricot preserves, melted and strained",
                                "originalName": "apricot preserves, melted and strained",
                                "metaInformation": ["melted"],
                                "meta": ["melted"],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/apricot-jam.jpg",
                            },
                        ],
                        "usedIngredients": [
                            {
                                "id": 1079003,
                                "amount": 4.0,
                                "unit": "large",
                                "unitLong": "larges",
                                "unitShort": "large",
                                "aisle": "Produce",
                                "name": "red apples",
                                "original": "4 larges red apples, such as Golden Delicious, peeled, cored and cut into 1/4-inch-thick slices",
                                "originalString": "4 larges red apples, such as Golden Delicious, peeled, cored and cut into 1/4-inch-thick slices",
                                "originalName": "s red apples, such as Golden Delicious, peeled, cored and cut into 1/4-inch-thick slices",
                                "metaInformation": [
                                    "red",
                                    " such as golden delicious, peeled, cored and cut into 1/4-inch-thick slices ",
                                ],
                                "meta": [
                                    "red",
                                    " such as golden delicious, peeled, cored and cut into 1/4-inch-thick slices ",
                                ],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/red-delicious-apples.png",
                            }
                        ],
                        "unusedIngredients": [],
                        "likes": 3,
                    },
                    {
                        "id": 641803,
                        "title": "Easy & Delish! ~ Apple Crumble",
                        "image": "https://spoonacular.com/recipeImages/641803-312x231.jpg",
                        "imageType": "jpg",
                        "usedIngredientCount": 1,
                        "missedIngredientCount": 3,
                        "missedIngredients": [
                            {
                                "id": 1001,
                                "amount": 0.75,
                                "unit": "stick",
                                "unitLong": "sticks",
                                "unitShort": "stick",
                                "aisle": "Milk, Eggs, Other Dairy",
                                "name": "butter",
                                "original": "3/4 stick of butter",
                                "originalString": "3/4 stick of butter",
                                "originalName": "butter",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/butter-sliced.jpg",
                            },
                            {
                                "id": 2011,
                                "amount": 1.0,
                                "unit": "Dash",
                                "unitLong": "Dash",
                                "unitShort": "Dash",
                                "aisle": "Spices and Seasonings",
                                "name": "cloves ground",
                                "original": "Dash of ground cloves",
                                "originalString": "Dash of ground cloves",
                                "originalName": "ground cloves",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/cloves.jpg",
                            },
                            {
                                "id": 9156,
                                "amount": 1.0,
                                "unit": "",
                                "unitLong": "",
                                "unitShort": "",
                                "aisle": "Produce",
                                "name": "lemon zest",
                                "original": "1 Zest of lemon",
                                "originalString": "1 Zest of lemon",
                                "originalName": "Zest of lemon",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/zest-lemon.jpg",
                            },
                        ],
                        "usedIngredients": [
                            {
                                "id": 9003,
                                "amount": 3.0,
                                "unit": "",
                                "unitLong": "",
                                "unitShort": "",
                                "aisle": "Produce",
                                "name": "apples",
                                "original": "3 apples – sliced",
                                "originalString": "3 apples – sliced",
                                "originalName": "apples – sliced",
                                "metaInformation": ["sliced"],
                                "meta": ["sliced"],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
                            }
                        ],
                        "unusedIngredients": [],
                        "likes": 1,
                    },
                    {
                        "id": 73420,
                        "title": "Apple Or Peach Strudel",
                        "image": "https://spoonacular.com/recipeImages/73420-312x231.jpg",
                        "imageType": "jpg",
                        "usedIngredientCount": 1,
                        "missedIngredientCount": 3,
                        "missedIngredients": [
                            {
                                "id": 18371,
                                "amount": 1.0,
                                "unit": "tsp",
                                "unitLong": "teaspoon",
                                "unitShort": "tsp",
                                "aisle": "Baking",
                                "name": "baking powder",
                                "original": "1 tsp baking powder",
                                "originalString": "1 tsp baking powder",
                                "originalName": "baking powder",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/white-powder.jpg",
                            },
                            {
                                "id": 2010,
                                "amount": 1.0,
                                "unit": "tsp",
                                "unitLong": "teaspoon",
                                "unitShort": "tsp",
                                "aisle": "Spices and Seasonings",
                                "name": "cinnamon",
                                "original": "1 tsp cinnamon",
                                "originalString": "1 tsp cinnamon",
                                "originalName": "cinnamon",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
                            },
                            {
                                "id": 1123,
                                "amount": 1.0,
                                "unit": "",
                                "unitLong": "",
                                "unitShort": "",
                                "aisle": "Milk, Eggs, Other Dairy",
                                "name": "egg",
                                "original": "1 egg",
                                "originalString": "1 egg",
                                "originalName": "egg",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/egg.png",
                            },
                        ],
                        "usedIngredients": [
                            {
                                "id": 9003,
                                "amount": 6.0,
                                "unit": "large",
                                "unitLong": "larges",
                                "unitShort": "large",
                                "aisle": "Produce",
                                "name": "apples",
                                "original": "6 large baking apples",
                                "originalString": "6 large baking apples",
                                "originalName": "baking apples",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
                            }
                        ],
                        "unusedIngredients": [],
                        "likes": 0,
                    },
                    {
                        "id": 157103,
                        "title": "Apple Cinnamon Blondies",
                        "image": "https://spoonacular.com/recipeImages/157103-312x231.jpg",
                        "imageType": "jpg",
                        "usedIngredientCount": 1,
                        "missedIngredientCount": 4,
                        "missedIngredients": [
                            {
                                "id": 1001,
                                "amount": 0.5,
                                "unit": "cup",
                                "unitLong": "cups",
                                "unitShort": "cup",
                                "aisle": "Milk, Eggs, Other Dairy",
                                "name": "butter",
                                "original": "1/2 cup butter, melted",
                                "originalString": "1/2 cup butter, melted",
                                "originalName": "butter, melted",
                                "metaInformation": ["melted"],
                                "meta": ["melted"],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/butter-sliced.jpg",
                            },
                            {
                                "id": 2010,
                                "amount": 1.0,
                                "unit": "tsp",
                                "unitLong": "teaspoon",
                                "unitShort": "tsp",
                                "aisle": "Spices and Seasonings",
                                "name": "cinnamon",
                                "original": "1 tsp. cinnamon",
                                "originalString": "1 tsp. cinnamon",
                                "originalName": "cinnamon",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
                            },
                            {
                                "id": 1123,
                                "amount": 1.0,
                                "unit": "",
                                "unitLong": "",
                                "unitShort": "",
                                "aisle": "Milk, Eggs, Other Dairy",
                                "name": "egg",
                                "original": "1 egg",
                                "originalString": "1 egg",
                                "originalName": "egg",
                                "metaInformation": [],
                                "meta": [],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/egg.png",
                            },
                            {
                                "id": 2050,
                                "amount": 1.0,
                                "unit": "tsp",
                                "unitLong": "teaspoon",
                                "unitShort": "tsp",
                                "aisle": "Baking",
                                "name": "vanilla",
                                "original": "1 tsp. vanilla (paste or extract)",
                                "originalString": "1 tsp. vanilla (paste or extract)",
                                "originalName": "vanilla (paste or extract)",
                                "metaInformation": ["(paste or extract)"],
                                "meta": ["(paste or extract)"],
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/vanilla-extract.jpg",
                            },
                        ],
                        "usedIngredients": [
                            {
                                "id": 9003,
                                "amount": 0.5,
                                "unit": "cup",
                                "unitLong": "cups",
                                "unitShort": "cup",
                                "aisle": "Produce",
                                "name": "apple",
                                "original": "1/2 cup apple, finely diced",
                                "originalString": "1/2 cup apple, finely diced",
                                "originalName": "apple, finely diced",
                                "metaInformation": ["diced", "finely"],
                                "meta": ["diced", "finely"],
                                "extendedName": "diced apple",
                                "image": "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
                            }
                        ],
                        "unusedIngredients": [],
                        "likes": 0,
                    },
                ],
            ]
            mock_requests_get.return_value = mock_response

            # self.assertEqual(search_recipe_by_ingred("apples,flour,sugar"), None)
            self.assertEqual(
                search_recipe_by_ingred("apples,flour,sugar"),
                {
                    640352: "Cranberry Apple Crisp",
                    632660: "Apricot Glazed Apple Tart",
                    641803: "Easy & Delish! ~ Apple Crumble",
                    73420: "Apple Or Peach Strudel",
                    157103: "Apple Cinnamon Blondies",
                },
            )


if __name__ == "__main__":
    unittest.main()
